/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedMembersIndexRouteImport } from './routes/_authed/members/index'
import { Route as AuthedCampusesIndexRouteImport } from './routes/_authed/campuses/index'
import { Route as AuthedAttendanceIndexRouteImport } from './routes/_authed/attendance/index'
import { Route as AuthedMembersMemberIdRouteImport } from './routes/_authed/members/$memberId'
import { Route as AuthedCampusesCampusIdRouteImport } from './routes/_authed/campuses/$campusId'
import { Route as AuthedCampusesCategoryCategoryIdRouteImport } from './routes/_authed/campuses/category/$categoryId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMembersIndexRoute = AuthedMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCampusesIndexRoute = AuthedCampusesIndexRouteImport.update({
  id: '/campuses/',
  path: '/campuses/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAttendanceIndexRoute = AuthedAttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMembersMemberIdRoute = AuthedMembersMemberIdRouteImport.update({
  id: '/members/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCampusesCampusIdRoute = AuthedCampusesCampusIdRouteImport.update({
  id: '/campuses/$campusId',
  path: '/campuses/$campusId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCampusesCategoryCategoryIdRoute =
  AuthedCampusesCategoryCategoryIdRouteImport.update({
    id: '/campuses/category/$categoryId',
    path: '/campuses/category/$categoryId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof AuthedSettingsRoute
  '/campuses/$campusId': typeof AuthedCampusesCampusIdRoute
  '/members/$memberId': typeof AuthedMembersMemberIdRoute
  '/attendance/': typeof AuthedAttendanceIndexRoute
  '/campuses/': typeof AuthedCampusesIndexRoute
  '/members/': typeof AuthedMembersIndexRoute
  '/campuses/category/$categoryId': typeof AuthedCampusesCategoryCategoryIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/settings': typeof AuthedSettingsRoute
  '/': typeof AuthedIndexRoute
  '/campuses/$campusId': typeof AuthedCampusesCampusIdRoute
  '/members/$memberId': typeof AuthedMembersMemberIdRoute
  '/attendance': typeof AuthedAttendanceIndexRoute
  '/campuses': typeof AuthedCampusesIndexRoute
  '/members': typeof AuthedMembersIndexRoute
  '/campuses/category/$categoryId': typeof AuthedCampusesCategoryCategoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/campuses/$campusId': typeof AuthedCampusesCampusIdRoute
  '/_authed/members/$memberId': typeof AuthedMembersMemberIdRoute
  '/_authed/attendance/': typeof AuthedAttendanceIndexRoute
  '/_authed/campuses/': typeof AuthedCampusesIndexRoute
  '/_authed/members/': typeof AuthedMembersIndexRoute
  '/_authed/campuses/category/$categoryId': typeof AuthedCampusesCategoryCategoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/campuses/$campusId'
    | '/members/$memberId'
    | '/attendance/'
    | '/campuses/'
    | '/members/'
    | '/campuses/category/$categoryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/settings'
    | '/'
    | '/campuses/$campusId'
    | '/members/$memberId'
    | '/attendance'
    | '/campuses'
    | '/members'
    | '/campuses/category/$categoryId'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/settings'
    | '/_authed/'
    | '/_authed/campuses/$campusId'
    | '/_authed/members/$memberId'
    | '/_authed/attendance/'
    | '/_authed/campuses/'
    | '/_authed/members/'
    | '/_authed/campuses/category/$categoryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/members/': {
      id: '/_authed/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof AuthedMembersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/campuses/': {
      id: '/_authed/campuses/'
      path: '/campuses'
      fullPath: '/campuses/'
      preLoaderRoute: typeof AuthedCampusesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/attendance/': {
      id: '/_authed/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AuthedAttendanceIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/members/$memberId': {
      id: '/_authed/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof AuthedMembersMemberIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/campuses/$campusId': {
      id: '/_authed/campuses/$campusId'
      path: '/campuses/$campusId'
      fullPath: '/campuses/$campusId'
      preLoaderRoute: typeof AuthedCampusesCampusIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/campuses/category/$categoryId': {
      id: '/_authed/campuses/category/$categoryId'
      path: '/campuses/category/$categoryId'
      fullPath: '/campuses/category/$categoryId'
      preLoaderRoute: typeof AuthedCampusesCategoryCategoryIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedCampusesCampusIdRoute: typeof AuthedCampusesCampusIdRoute
  AuthedMembersMemberIdRoute: typeof AuthedMembersMemberIdRoute
  AuthedAttendanceIndexRoute: typeof AuthedAttendanceIndexRoute
  AuthedCampusesIndexRoute: typeof AuthedCampusesIndexRoute
  AuthedMembersIndexRoute: typeof AuthedMembersIndexRoute
  AuthedCampusesCategoryCategoryIdRoute: typeof AuthedCampusesCategoryCategoryIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedCampusesCampusIdRoute: AuthedCampusesCampusIdRoute,
  AuthedMembersMemberIdRoute: AuthedMembersMemberIdRoute,
  AuthedAttendanceIndexRoute: AuthedAttendanceIndexRoute,
  AuthedCampusesIndexRoute: AuthedCampusesIndexRoute,
  AuthedMembersIndexRoute: AuthedMembersIndexRoute,
  AuthedCampusesCategoryCategoryIdRoute: AuthedCampusesCategoryCategoryIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
