/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FollowupsRouteImport } from './routes/followups'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as CampusesIndexRouteImport } from './routes/campuses/index'
import { Route as AttendanceIndexRouteImport } from './routes/attendance/index'
import { Route as UpdateTokenRouteImport } from './routes/update.$token'
import { Route as MembersMemberIdRouteImport } from './routes/members/$memberId'
import { Route as CampusesCampusIdRouteImport } from './routes/campuses/$campusId'
import { Route as CampusesCategoryCategoryIdRouteImport } from './routes/campuses/category/$categoryId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowupsRoute = FollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusesIndexRoute = CampusesIndexRouteImport.update({
  id: '/campuses/',
  path: '/campuses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceIndexRoute = AttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdateTokenRoute = UpdateTokenRouteImport.update({
  id: '/update/$token',
  path: '/update/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberIdRoute = MembersMemberIdRouteImport.update({
  id: '/members/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusesCampusIdRoute = CampusesCampusIdRouteImport.update({
  id: '/campuses/$campusId',
  path: '/campuses/$campusId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusesCategoryCategoryIdRoute =
  CampusesCategoryCategoryIdRouteImport.update({
    id: '/campuses/category/$categoryId',
    path: '/campuses/category/$categoryId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/followups': typeof FollowupsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/campuses/$campusId': typeof CampusesCampusIdRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/update/$token': typeof UpdateTokenRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/campuses/': typeof CampusesIndexRoute
  '/members/': typeof MembersIndexRoute
  '/campuses/category/$categoryId': typeof CampusesCategoryCategoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/followups': typeof FollowupsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/campuses/$campusId': typeof CampusesCampusIdRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/update/$token': typeof UpdateTokenRoute
  '/attendance': typeof AttendanceIndexRoute
  '/campuses': typeof CampusesIndexRoute
  '/members': typeof MembersIndexRoute
  '/campuses/category/$categoryId': typeof CampusesCategoryCategoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/followups': typeof FollowupsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/campuses/$campusId': typeof CampusesCampusIdRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/update/$token': typeof UpdateTokenRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/campuses/': typeof CampusesIndexRoute
  '/members/': typeof MembersIndexRoute
  '/campuses/category/$categoryId': typeof CampusesCategoryCategoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/followups'
    | '/login'
    | '/settings'
    | '/campuses/$campusId'
    | '/members/$memberId'
    | '/update/$token'
    | '/attendance/'
    | '/campuses/'
    | '/members/'
    | '/campuses/category/$categoryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/followups'
    | '/login'
    | '/settings'
    | '/campuses/$campusId'
    | '/members/$memberId'
    | '/update/$token'
    | '/attendance'
    | '/campuses'
    | '/members'
    | '/campuses/category/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/followups'
    | '/login'
    | '/settings'
    | '/campuses/$campusId'
    | '/members/$memberId'
    | '/update/$token'
    | '/attendance/'
    | '/campuses/'
    | '/members/'
    | '/campuses/category/$categoryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FollowupsRoute: typeof FollowupsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  CampusesCampusIdRoute: typeof CampusesCampusIdRoute
  MembersMemberIdRoute: typeof MembersMemberIdRoute
  UpdateTokenRoute: typeof UpdateTokenRoute
  AttendanceIndexRoute: typeof AttendanceIndexRoute
  CampusesIndexRoute: typeof CampusesIndexRoute
  MembersIndexRoute: typeof MembersIndexRoute
  CampusesCategoryCategoryIdRoute: typeof CampusesCategoryCategoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followups': {
      id: '/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof FollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campuses/': {
      id: '/campuses/'
      path: '/campuses'
      fullPath: '/campuses/'
      preLoaderRoute: typeof CampusesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/': {
      id: '/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AttendanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update/$token': {
      id: '/update/$token'
      path: '/update/$token'
      fullPath: '/update/$token'
      preLoaderRoute: typeof UpdateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$memberId': {
      id: '/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof MembersMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campuses/$campusId': {
      id: '/campuses/$campusId'
      path: '/campuses/$campusId'
      fullPath: '/campuses/$campusId'
      preLoaderRoute: typeof CampusesCampusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campuses/category/$categoryId': {
      id: '/campuses/category/$categoryId'
      path: '/campuses/category/$categoryId'
      fullPath: '/campuses/category/$categoryId'
      preLoaderRoute: typeof CampusesCategoryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FollowupsRoute: FollowupsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  CampusesCampusIdRoute: CampusesCampusIdRoute,
  MembersMemberIdRoute: MembersMemberIdRoute,
  UpdateTokenRoute: UpdateTokenRoute,
  AttendanceIndexRoute: AttendanceIndexRoute,
  CampusesIndexRoute: CampusesIndexRoute,
  MembersIndexRoute: MembersIndexRoute,
  CampusesCategoryCategoryIdRoute: CampusesCategoryCategoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
